[tool.poetry]
name = "mbuilder"
version = "0.1.0"
description = ""
authors = ["twilight2017 <liuzixuanp@163.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
